osx_image: xcode8.2
language: objective-c
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/RAGVersionNumber.xcworkspace -scheme RAGVersionNumber-Example -sdk iphonesimulator10.2 -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.2' ONLY_ACTIVE_ARCH=NO
- pod lib lint --allow-warnings
after_success:
  - bash <(curl -s https://codecov.io/bash)